sudo: required

language: node_js

services:
  - docker

node_js:
  - "lts/*"

addons:
  chrome: stable

before_script:
      - "sudo chown root /opt/google/chrome/chrome-sandbox"
      - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

install:
  - yarn
  - npm install -g codecov

script:
  - yarn lint
  - yarn build
  - yarn test-headless
  - codecov -f ./coverage/ng-test/lcov.info
  - docker run -d -p 127.0.0.1:8080:8080 --name chatty-server kaitoedter/chatty
  - yarn e2e-headless
