sudo: required

language: node_js

node_js:
  - "lts/*"

addons:
  chrome: stable

before_script:
      - "sudo chown root /opt/google/chrome/chrome-sandbox"
      - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

install:
  - yarn
  - npm install -g codecov

script:
  - yarn lint
  - yarn build
  - yarn test-headless
  - codecov -f ./coverage/ng-test/lcov.info
  - yarn e2e-headless
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
  - if [[ ($TRAVIS_BRANCH == master) && ($TRAVIS_PULL_REQUEST == false) ]] ; then
      curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
      sh trigger-travis.sh toedter chatty $TRAVIS_ACCESS_TOKEN
      sh trigger-travis.sh toedter movies-demo $TRAVIS_ACCESS_TOKEN
    fi
